apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-mtnz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-mtnz
    app.kubernetes.io/part-of: hacbs-demo-test-app-flze
  name: test-component-mtnz
  namespace: hacbs-e2e-uraz
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-mtnz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-mtnz
    spec:
      containers:
      - image: quay.io/psturc/test-images:507fbfae4de8492484b602755b82de24
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
